# Generated by Django 3.2.5 on 2021-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=100)),
                ('vote_average', models.CharField(max_length=20)),
                ('vote_count', models.CharField(max_length=20)),
            ],
        ),
    ]
